### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [xkevio/CUDA-Raytracer#1]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm building your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/119220693-51293480-bb1e-11eb-83bb-aa2f9061d307.png)

thank you  
best regards to you  
William

**Comment by xkevio** [comment]
Hey, thanks for checking out this project! Try including the `<iterator>` header, I probably forgot to do that as some other header I use already included it but one should always explicitely include the headers they need and not rely on compiler implementations
